#define FACTION_RELATION_LEVEL_HATED -3 //-100 to -75
#define FACTION_RELATION_LEVEL_DISLIKED -2 // -75 to -50
#define FACTION_RELATION_LEVEL_DISTRUSTED -1 // -50 to -25
#define FACTION_RELATION_LEVEL_NEUTRAL 0 //-25 to 25
#define FACTION_RELATION_LEVEL_APPRECIATED 1 //25 to 50
#define FACTION_RELATION_LEVEL_FRIENDLY 2 //50 to 75
#define FACTION_RELATION_LEVEL_BELOVED 3 //75 to 100

#define FACTION_RELATION_LEVEL_HATED_THRESHOLD -75
#define FACTION_RELATION_LEVEL_DISLIKED_THRESHOLD -50
#define FACTION_RELATION_LEVEL_DISTRUSTED_THRESHOLD -25
#define FACTION_RELATION_LEVEL_APPRECIATED_THRESHOLD 25
#define FACTION_RELATION_LEVEL_FRIENDLY_THRESHOLD 50
#define FACTION_RELATION_LEVEL_BELOVED_THRESHOLD 75


#define COMMS_REQUEST_ACCEPTED 1
#define COMMS_REQUEST_DENIED 2
